//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoLib.Resources.GeoRes", typeof(GeoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF	Africa	6255146
        ///AS	Asia	6255147
        ///EU	Europe	6255148
        ///NA	North America	6255149
        ///OC	Oceania	6255151
        ///SA	South America	6255150
        ///AN	Antarctica	6255152.
        /// </summary>
        public static string continents {
            get {
                return ResourceManager.GetString("continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping country: {0}.
        /// </summary>
        public static string CountryHelper_ParseCountries_Skipping_country___0_ {
            get {
                return ResourceManager.GetString("CountryHelper_ParseCountries_Skipping_country___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined language {0}.
        /// </summary>
        public static string CountryHelper_ParseCountries_Undefined_language__0_ {
            get {
                return ResourceManager.GetString("CountryHelper_ParseCountries_Undefined_language__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A	country, state, region,...
        ///H	stream, lake, ...
        ///L	parks,area, ...
        ///P	city, village,...
        ///R	road, railroad
        ///S	spot, building, farm
        ///T	mountain,hill,rock,...
        ///U	undersea
        ///V	forest,heath,...
        ///.
        /// </summary>
        public static string fclasses {
            get {
                return ResourceManager.GetString("fclasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	първостепенна административна единица 	a primary administrative division of a country, such as a state in the United States
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	второстепенна административна единица 	a subdivision of a first-order administrative division
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	третостепенна административна единица 	a subdivision of a second-order  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_bg {
            get {
                return ResourceManager.GetString("featureCodes_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	first-order administrative division	a primary administrative division of a country, such as a state in the United States
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	second-order administrative division	a subdivision of a first-order administrative division
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	third-order administrative division	a subdivision of a second-order admi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_en {
            get {
                return ResourceManager.GetString("featureCodes_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	primær administrativ inndeling	a primary administrative division of a country, such as a state in the United States
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	sekundær administrativ inndeling	a subdivision of a first-order administrative division
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	administrativ inndeling av tredje grad	a subdivision of a second-order administra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_nb {
            get {
                return ResourceManager.GetString("featureCodes_nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	primær administrativ inndeling	a primary administrative division of a country, such as a state in the United States
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	sekundær administrativ inndeling	a subdivision of a first-order administrative division
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	administrativ inndeling av tredje grad	a subdivision of a second-order administra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_nn {
            get {
                return ResourceManager.GetString("featureCodes_nn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	primær administrativ inndeling	a primary administrative division of a country, such as a state in the United States
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	sekundær administrativ inndeling	a subdivision of a first-order administrative division
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	administrativ inndeling av tredje grad	a subdivision of a second-order administra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_no {
            get {
                return ResourceManager.GetString("featureCodes_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	политико-административное деление первого порядка	первоначальное политико-административное  деление, например, деление США на штаты
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	политико-административное деление второго порядка	дальнейшее деление политико-административного деления первого порядка
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	политико-административное деление тре [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_ru {
            get {
                return ResourceManager.GetString("featureCodes_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.ADM1	första ordningens administrativ avdelning	a primary administrative division of a country, such as a state in the United States
        ///A.ADM1H	historical first-order administrative division	a former first-order administrative division
        ///A.ADM2	andra ordningens administrativ avdelning	a subdivision of a first-order administrative division
        ///A.ADM2H	historical second-order administrative division	a former second-order administrative division
        ///A.ADM3	tredje ordningens administrativ avdelning	a subdivision of a secon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string featureCodes_sv {
            get {
                return ResourceManager.GetString("featureCodes_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _	_	_	Neutral language
        ///afa	afa		Afro-Asiatic languages
        ///alg	alg		Algonquian languages
        ///apa	apa		Apache languages
        ///art	art		Artificial languages
        ///ath	ath		Athapascan languages
        ///aus	aus		Australian languages
        ///bad	bad		Banda languages
        ///bai	bai		Bamileke languages
        ///bat	bat		Baltic languages
        ///ber	ber		Berber languages
        ///bih	bih	bh	Bihari 
        ///bnt	bnt		Bantu (Other)
        ///btk	btk		Batak languages
        ///cai	cai		Central American Indian languages
        ///cau	cau		Caucasian languages
        ///cel	cel		Celtic languages
        ///cmc	cmc		Chamic languages
        ///cpe	cpe		Creole [rest of string was truncated]&quot;;.
        /// </summary>
        public static string iso_languagecodes {
            get {
                return ResourceManager.GetString("iso_languagecodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI	Africa/Abidjan	0.0	0.0	0.0
        ///GH	Africa/Accra	0.0	0.0	0.0
        ///ET	Africa/Addis_Ababa	3.0	3.0	3.0
        ///DZ	Africa/Algiers	1.0	1.0	1.0
        ///ER	Africa/Asmara	3.0	3.0	3.0
        ///ML	Africa/Bamako	0.0	0.0	0.0
        ///CF	Africa/Bangui	1.0	1.0	1.0
        ///GM	Africa/Banjul	0.0	0.0	0.0
        ///GW	Africa/Bissau	0.0	0.0	0.0
        ///MW	Africa/Blantyre	2.0	2.0	2.0
        ///CG	Africa/Brazzaville	1.0	1.0	1.0
        ///BI	Africa/Bujumbura	2.0	2.0	2.0
        ///EG	Africa/Cairo	2.0	2.0	2.0
        ///MA	Africa/Casablanca	0.0	1.0	0.0
        ///ES	Africa/Ceuta	1.0	2.0	1.0
        ///GN	Africa/Conakry	0.0	0.0	0.0
        ///SN	Africa/Dak [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZones {
            get {
                return ResourceManager.GetString("timeZones", resourceCulture);
            }
        }
    }
}
