// <auto-generated />
namespace GeoLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CountryAreaDouble_Remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountryAreaDouble_Remove));
        
        string IMigrationMetadata.Id
        {
            get { return "201404221055273_CountryAreaDouble_Remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
